name: build and check
on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install autoconf-archive lcov libtss2-dev libtss2-tcti-tabrmd0 tpm2-abrmd tpm2-tools

    - name: Build TPM2 simulator
      run: |
        wget --no-verbose https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1637.tar.gz
        mkdir ibmtpm
        tar xfz ibmtpm1637.tar.gz -C ibmtpm
        cd ibmtpm/src
        make

    - name: Build openssl
      run: |
        wget --no-verbose https://github.com/openssl/openssl/archive/master.zip
        unzip -q master.zip
        cd openssl-master
        if [[ ${{ matrix.compiler }} == 'clang' ]]; then
          OSSL_EXTRA="linux-x86_64-clang enable-asan"
        fi
        # disable all unnecessary features
        ./Configure no-deprecated no-aria no-async no-autoload-config no-bf \
                    no-blake2 no-cast no-chacha no-cms no-cmp \
                    no-comp no-ct no-des no-dgram no-dh no-dsa no-ec2m \
                    no-filenames no-fips no-fips-securitychecks no-gost no-idea \
                    no-ktls no-makedepend no-md4 no-multiblock no-nextprotoneg \
                    no-ocb no-ocsp no-poly1305 no-psk no-rc2 no-rc4 no-rfc3779 \
                    no-rmd160 no-seed no-siphash no-siv no-sm3 no-sm4 no-srp \
                    no-srtp no-ssl3-method no-tests no-ts no-ui-console no-whirlpool \
                    $OSSL_EXTRA
        make build_sw
        sudo make install_sw install_ssldirs
        sudo ldconfig

    - name: Configure tpm2-openssl (gcc)
      if: matrix.compiler == 'gcc'
      run: |
        ./bootstrap
        ./configure CC=gcc --enable-code-coverage --enable-debug

    - name: Configure tpm2-openssl (clang)
      if: matrix.compiler == 'clang'
      run: |
        ./bootstrap
        ./configure CC=clang --enable-asan --enable-debug

    - name: Build tpm2-openssl
      run: |
        make
        sudo make install

    - name: Start TPM2 simulator
      run: |
        export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork`
        echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
        ibmtpm/src/tpm_server &
        tpm2-abrmd --session --tcti mssim:host=localhost,port=2321 &
        echo "TCTI_ADDRESS=tabrmd:bus_name=com.intel.tss2.Tabrmd,bus_type=session" >> $GITHUB_ENV
        sleep 1

    - name: Run tests
      run: |
        openssl version
        tpm2_getcap properties-fixed | head -n 20
        make check
      env:
        TPM2TOOLS_TCTI: ${{ env.TCTI_ADDRESS }}
        TPM2OPENSSL_TCTI: ${{ env.TCTI_ADDRESS }}

    - name: Check code coverage (gcc)
      if: matrix.compiler == 'gcc'
      run: |
        make check-code-coverage
      env:
        TPM2TOOLS_TCTI: ${{ env.TCTI_ADDRESS }}
        TPM2OPENSSL_TCTI: ${{ env.TCTI_ADDRESS }}

    - name: Submit code coverage (gcc)
      if: matrix.compiler == 'gcc'
      uses: codecov/codecov-action@v1.2.1

    - name: Archive log files
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report-${{ matrix.compiler }}
        path: |
          *.log
          test/*.log
